export const routes = {
	HOME: '/',
	LOGIN: '/login',
	REGISTER: '/register',
	DASHBOARD: '/dashboard',
	EMAIL_VERIFIED: '/email-verified',
	ANIME: '/anime',
	MANGA: '/manga',
	FAVORITES: '/favorites',
	SETTINGS: '/settings',
	PROFILE: '/profile',
	LOGOUT: '/logout',
	FORGOT_PASSWORD: '/forgot-password',
	RESET_PASSWORD: '/reset-password/:token',
};
